ita-social-projects/TeachUA

- .gitignore
- pom.xml
- src/main/java/com/softserve/teachua/ServletInitializer.java
- src/main/java/com/softserve/teachua/TeachuaApplication.java
- src/main/resources/application.properties
- src/test/java/com/softserve/teachua/TeachuaApplicationTests.java
> add project configuration

- src/main/java/com/softserve/teachua/model/Activity.java
- src/main/java/com/softserve/teachua/model/Club.java
> added activity and club entity

- src/main/java/com/softserve/teachua/model/ClubContact.java
- src/main/java/com/softserve/teachua/model/Rating.java
> ClubContact, Rating models were added

- src/main/java/com/softserve/teachua/model/News.java
- src/main/java/com/softserve/teachua/model/Role.java
- src/main/java/com/softserve/teachua/model/User.java
> added model for news, added fields to user and roles entities

- src/main/resources/static/images/style.css
> Designed clubs page

- src/main/java/com/softserve/teachua/model/Rating.java
- src/main/java/com/softserve/teachua/model/Role.java
- src/main/java/com/softserve/teachua/model/User.java
- src/main/resources/application.properties
> added field and annotations to user

- src/main/java/com/softserve/teachua/controller/ClubsController.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/resources/static/images/map/google-maps-marker.svg
- src/main/resources/templates/clubs.html
- src/main/resources/templates/map-page.html
- src/main/resources/templates/project-page.html
> small fixes with styles, added redirect to main controller

- src/main/resources/templates/project-page.html
> project page updated

- src/main/java/com/softserve/teachua/controller/ClubsController.java
> clubsController fixed

- src/main/java/com/softserve/teachua/repository/GoogleMapRepository.java
- src/main/resources/templates/project-page.html
> project-page logo fixed

- src/main/java/com/softserve/teachua/controller/CategoryController.java
- src/main/java/com/softserve/teachua/dto/controller/CategoryResponse.java
- src/main/java/com/softserve/teachua/dto/service/CategoryProfile.java
- src/main/java/com/softserve/teachua/model/Category.java
- src/main/java/com/softserve/teachua/repository/CategoryRepository.java
- src/main/java/com/softserve/teachua/service/CategoryService.java
- src/main/java/com/softserve/teachua/service/impl/CategoryServiceImpl.java
> add category repo, service, update controller

- src/main/java/com/softserve/teachua/dto/controller/ClubResponse.java
- src/main/java/com/softserve/teachua/dto/controller/SuccessCreatedClub.java
- src/main/java/com/softserve/teachua/dto/service/ClubProfile.java
- src/main/java/com/softserve/teachua/model/Club.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
> refactored methods in clubserviceimpl, added full entities of club dto.

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/converter/DtoConverter.java
- src/main/java/com/softserve/teachua/dto/search/SearchClubDto.java
- src/main/java/com/softserve/teachua/exception/AlreadyExistException.java
- src/main/java/com/softserve/teachua/exception/BadRequestException.java
- src/main/java/com/softserve/teachua/exception/DatabaseRepositoryException.java
- src/main/java/com/softserve/teachua/exception/MethodNotSupportedException.java
- src/main/java/com/softserve/teachua/exception/NotExistException.java
- src/main/java/com/softserve/teachua/exception/WrongAuthenticationException.java
- src/main/java/com/softserve/teachua/exception/handler/CustomExceptionHandler.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/ClubService.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
> Added search for clubs by name and city name

- src/main/java/com/softserve/teachua/controller/FeedbackController.java
- src/main/java/com/softserve/teachua/dto/controller/CenterResponse.java
- src/main/java/com/softserve/teachua/dto/controller/FeedbackResponse.java
- src/main/java/com/softserve/teachua/dto/controller/SuccessCreatedCenter.java
- src/main/java/com/softserve/teachua/dto/controller/SuccessCreatedFeedback.java
- src/main/java/com/softserve/teachua/dto/service/CenterProfile.java
- src/main/java/com/softserve/teachua/dto/service/FeedbackProfile.java
- src/main/java/com/softserve/teachua/model/Feedback.java
- src/main/java/com/softserve/teachua/repository/FeedbackRepository.java
- src/main/java/com/softserve/teachua/service/CategoryService.java
- src/main/java/com/softserve/teachua/service/FeedbackService.java
- src/main/java/com/softserve/teachua/service/impl/CategoryServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/FeedbackServiceImpl.java
> Feedback serv

- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/dto/service/SearchClubProfile.java
- src/main/java/com/softserve/teachua/model/Category.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/ClubService.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/resources/data.sql
> Clubs search

- src/main/java/com/softserve/teachua/controller/CityController.java
- src/main/java/com/softserve/teachua/service/CityService.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/CityServiceImpl.java
> added comments to center and city services

- src/main/java/com/softserve/teachua/controller/CityController.java
- src/main/java/com/softserve/teachua/dto/district/DistrictProfile.java
- src/main/java/com/softserve/teachua/dto/district/DistrictResponse.java
- src/main/java/com/softserve/teachua/dto/district/SuccessCreatedDistrict.java
- src/main/java/com/softserve/teachua/dto/station/StationProfile.java
- src/main/java/com/softserve/teachua/dto/station/StationResponse.java
- src/main/java/com/softserve/teachua/dto/station/SuccesCreatedStation.java
- src/main/java/com/softserve/teachua/model/Category.java
- src/main/java/com/softserve/teachua/model/Center.java
- src/main/java/com/softserve/teachua/model/Club.java
- src/main/java/com/softserve/teachua/model/District.java
- src/main/java/com/softserve/teachua/model/News.java
- src/main/java/com/softserve/teachua/model/Role.java
- src/main/java/com/softserve/teachua/model/Station.java
- src/main/java/com/softserve/teachua/model/User.java
- src/main/java/com/softserve/teachua/service/CityService.java
- src/main/java/com/softserve/teachua/service/impl/CityServiceImpl.java
- src/main/resources/data.sql
> Added new entities & DTOs, all models updated

- src/main/java/com/softserve/teachua/Application.java
- src/main/java/com/softserve/teachua/controller/SearchController.java
- src/main/java/com/softserve/teachua/dto/search/SearchClubProfile.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/ClubService.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
> changed search logic, added possibility to find by District and Stations

- src/main/java/com/softserve/teachua/controller/StationController.java
- src/main/java/com/softserve/teachua/dto/club/ClubProfile.java
- src/main/java/com/softserve/teachua/dto/club/ClubResponse.java
- src/main/java/com/softserve/teachua/dto/club/SuccessCreatedClub.java
- src/main/java/com/softserve/teachua/dto/club/SuccessUpdatedClub.java
- src/main/java/com/softserve/teachua/dto/station/SuccessCreatedStation.java
- src/main/java/com/softserve/teachua/repository/StationRepository.java
- src/main/java/com/softserve/teachua/service/StationService.java
- src/main/java/com/softserve/teachua/service/impl/StationServiceImpl.java
> added station controllers, repository and service layers.

- src/main/java/com/softserve/teachua/controller/CategoryController.java
- src/main/java/com/softserve/teachua/controller/CenterController.java
- src/main/java/com/softserve/teachua/controller/CityController.java
- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/controller/FeedbackController.java
- src/main/java/com/softserve/teachua/controller/NewsController.java
- src/main/java/com/softserve/teachua/controller/RoleController.java
- src/main/java/com/softserve/teachua/controller/SearchController.java
- src/main/java/com/softserve/teachua/controller/StationController.java
- src/main/java/com/softserve/teachua/controller/UserController.java
- src/main/java/com/softserve/teachua/controller/marker/Api.java
- src/main/java/com/softserve/teachua/controller/user/LoginController.java
- src/main/java/com/softserve/teachua/controller/user/RegistrationController.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/resources/application.properties
> deleted /api from properties, added /api as mark interface

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/controller/MainController.java
- src/main/resources/data.sql
> added redirect to front

- src/main/java/com/softserve/teachua/config/ApplicationConfig.java
- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/controller/MainController.java
- src/main/java/com/softserve/teachua/converter/ModelMapper.java
- src/main/java/com/softserve/teachua/security/PasswordEncoder.java
> added AppConfig, added main controller

- src/main/java/com/softserve/teachua/config/ApplicationConfig.java
- src/main/java/com/softserve/teachua/exception/JsonWriteException.java
- src/main/java/com/softserve/teachua/exception/handler/CustomExceptionHandler.java
- src/main/java/com/softserve/teachua/model/Archive.java
- src/main/java/com/softserve/teachua/model/Category.java
- src/main/java/com/softserve/teachua/model/Center.java
- src/main/java/com/softserve/teachua/model/Club.java
- src/main/java/com/softserve/teachua/model/District.java
- src/main/java/com/softserve/teachua/model/Feedback.java
- src/main/java/com/softserve/teachua/model/News.java
- src/main/java/com/softserve/teachua/model/Role.java
- src/main/java/com/softserve/teachua/model/Station.java
- src/main/java/com/softserve/teachua/model/User.java
- src/main/java/com/softserve/teachua/model/marker/Archivable.java
- src/main/java/com/softserve/teachua/repository/ArchiveRepository.java
- src/main/java/com/softserve/teachua/service/ArchiveService.java
- src/main/java/com/softserve/teachua/service/impl/ArchiveServiceImpl.java
> Added archive entity and archiveService

- src/main/java/com/softserve/teachua/controller/CategoryController.java
- src/main/java/com/softserve/teachua/controller/CenterController.java
- src/main/java/com/softserve/teachua/controller/marker/Api.java
- src/main/java/com/softserve/teachua/dto/center/CenterProfile.java
- src/main/java/com/softserve/teachua/dto/center/SuccessCreatedCenter.java
- src/main/java/com/softserve/teachua/model/Archive.java
- src/main/java/com/softserve/teachua/model/Category.java
- src/main/java/com/softserve/teachua/service/CenterService.java
- src/main/java/com/softserve/teachua/service/impl/ArchiveServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/CategoryServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/resources/data.sql
> added delete method to center

- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/dto/club/ClubResponse.java
- src/main/java/com/softserve/teachua/dto/search/SimilarClubProfile.java
- src/main/java/com/softserve/teachua/model/Category.java
- src/main/java/com/softserve/teachua/model/Club.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/ClubService.java
- src/main/java/com/softserve/teachua/service/impl/ArchiveServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/resources/data.sql
> Center delete method

- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/controller/UserController.java
- src/main/java/com/softserve/teachua/service/ClubService.java
- src/main/java/com/softserve/teachua/service/UserService.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
> Club user delete method

- src/main/java/com/softserve/teachua/controller/CategoryController.java
- src/main/java/com/softserve/teachua/service/impl/CategoryServiceImpl.java
> Category delete method

- src/main/java/com/softserve/teachua/service/impl/NewsServiceImpl.java
> Updated deleteNewsById method to NewsServiceImpl

- src/main/java/com/softserve/teachua/controller/CityController.java
- src/main/java/com/softserve/teachua/controller/RoleController.java
- src/main/java/com/softserve/teachua/service/CityService.java
- src/main/java/com/softserve/teachua/service/RoleService.java
- src/main/java/com/softserve/teachua/service/impl/CityServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/RoleServiceImpl.java
> City and role delete method

- pom.xml
- src/main/java/com/softserve/teachua/dto/category/SuccessCreatedCategory.java
- src/test/java/com/softserve/teachua/service/CategoryServiceTest.java
- src/test/java/com/softserve/teachua/service/CenterServiceTest.java
> Added center and category unit tests

- src/main/java/com/softserve/teachua/security/JwtFilter.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/FeedbackServiceImpl.java
> change filter, added center and feedback delete methods

- src/main/java/com/softserve/teachua/controller/FeedbackController.java
- src/main/java/com/softserve/teachua/dto/feedback/FeedbackProfile.java
- src/main/java/com/softserve/teachua/dto/feedback/FeedbackResponse.java
- src/main/java/com/softserve/teachua/dto/feedback/SuccessCreatedFeedback.java
- src/main/java/com/softserve/teachua/model/Category.java
- src/main/java/com/softserve/teachua/model/Feedback.java
- src/main/java/com/softserve/teachua/repository/FeedbackRepository.java
- src/main/java/com/softserve/teachua/service/FeedbackService.java
- src/main/java/com/softserve/teachua/service/impl/FeedbackServiceImpl.java
- src/main/resources/data.sql
> changed feedback dto and model

- src/main/java/com/softserve/teachua/config/ApplicationConfig.java
> fixed filter

- src/main/java/com/softserve/teachua/model/Role.java
- src/main/java/com/softserve/teachua/service/impl/CategoryServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
- src/test/java/com/softserve/teachua/service/UserServiceTest.java
- src/test/resources/application.properties
> UserService unit tests, fixed delete for Category and User

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/controller/UserController.java
- src/main/java/com/softserve/teachua/dto/user/SuccessUpdatedUser.java
- src/main/java/com/softserve/teachua/dto/user/UserProfile.java
- src/main/java/com/softserve/teachua/dto/user/UserResponse.java
- src/main/java/com/softserve/teachua/model/User.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/ClubService.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/resources/data.sql
> Minor user update

- src/main/java/com/softserve/teachua/controller/ContactTypeController.java
- src/main/java/com/softserve/teachua/dto/contactType/ContactTypeProfile.java
- src/main/java/com/softserve/teachua/dto/contactType/ContactTypeResponse.java
- src/main/java/com/softserve/teachua/dto/contactType/SuccessCreatedContactType.java
- src/main/java/com/softserve/teachua/model/ContactType.java
- src/main/java/com/softserve/teachua/repository/ContactTypeRepository.java
- src/main/java/com/softserve/teachua/service/ContactTypeService.java
- src/main/java/com/softserve/teachua/service/impl/ContactTypeServiceImpl.java
> Contact type 

- pom.xml
- src/main/java/com/softserve/teachua/dto/search/SearchClubProfile.java
- src/main/java/com/softserve/teachua/dto/search/SearchPossibleResponse.java
- src/main/java/com/softserve/teachua/dto/search/SimilarClubProfile.java
- src/main/java/com/softserve/teachua/service/impl/CityServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/test/java/com/softserve/teachua/service/CityServiceTest.java
- src/test/java/com/softserve/teachua/service/ClubServiceTest.java
> City and club service unit tests

- src/main/java/com/softserve/teachua/dto/feedback/FeedbackProfile.java
- src/test/java/com/softserve/teachua/service/FeedbackServiceTest.java
- src/test/java/com/softserve/teachua/service/RoleServiceTest.java
> Role and feedback service tests

- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/dto/city/CityProfile.java
- src/main/java/com/softserve/teachua/dto/city/SuccessCreatedCity.java
- src/main/java/com/softserve/teachua/dto/district/DistrictProfile.java
- src/main/java/com/softserve/teachua/dto/district/DistrictResponse.java
- src/main/java/com/softserve/teachua/dto/district/SuccessCreatedDistrict.java
- src/main/java/com/softserve/teachua/dto/search/AdvancedSearchClubProfile.java
- src/main/java/com/softserve/teachua/dto/search/SearchClubProfile.java
- src/main/java/com/softserve/teachua/repository/CityRepository.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/repository/DistrictRepository.java
- src/main/java/com/softserve/teachua/service/ClubService.java
- src/main/java/com/softserve/teachua/service/impl/CityServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/DistrictServiceImpl.java
- src/main/java/com/softserve/teachua/utils/CategoryUtil.java
> added admin city/district editing

- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/ClubService.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/resources/application.properties
> Club contr

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/controller/UserController.java
- src/test/java/com/softserve/teachua/service/CategoryServiceTest.java
- src/test/java/com/softserve/teachua/service/ComplaintServiceTest.java
- src/test/resources/application.properties
> Complaints

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/security/JwtFilter.java
- src/main/java/com/softserve/teachua/security/UserPrincipal.java
- src/main/resources/data.sql
> change spring security config

- pom.xml
> change pom.xml poi version from 5.0.0 to 4.1.1

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/dto/category/CategoryProfile.java
- src/main/java/com/softserve/teachua/dto/category/CategoryResponse.java
- src/main/java/com/softserve/teachua/dto/category/SuccessCreatedCategory.java
> Develop UI and back form for add/edit categories.

- src/main/java/com/softserve/teachua/converter/ClubToClubResponseConverter.java
- src/main/resources/data.sql
> add couple clubs to data.sql

- src/main/java/com/softserve/teachua/dto/center/CenterProfile.java
- src/main/java/com/softserve/teachua/dto/center/CenterResponse.java
- src/main/java/com/softserve/teachua/dto/center/SuccessCreatedCenter.java
- src/main/java/com/softserve/teachua/dto/club/ClubProfile.java
- src/main/java/com/softserve/teachua/dto/location/LocationProfile.java
- src/main/java/com/softserve/teachua/model/Center.java
- src/main/java/com/softserve/teachua/model/Club.java
- src/main/java/com/softserve/teachua/model/Location.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/resources/application.yaml
- src/test/java/com/softserve/teachua/service/CenterServiceTest.java
> change center profile

- src/main/java/com/softserve/teachua/dto/category/SuccessCreatedCategory.java
- src/main/java/com/softserve/teachua/model/Club.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/DataLoaderServiceImpl.java
- src/main/resources/data.sql
> fix clubs files, data.sql and SuccessCreatedCategory

- src/main/java/com/softserve/teachua/dto/category/CategoryProfile.java
- src/main/java/com/softserve/teachua/service/impl/CategoryServiceImpl.java
> Add sort categories on backend

- src/main/java/com/softserve/teachua/repository/CategoryRepository.java
- src/main/java/com/softserve/teachua/service/impl/CategoryServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ExcelParserServiceImpl.java
- src/main/java/com/softserve/teachua/utils/ExcelRowParser.java
- src/main/resources/data.sql
> fix parsing and loading data from exel to db

- src/main/java/com/softserve/teachua/controller/user/RegistrationController.java
- src/main/java/com/softserve/teachua/dto/user/SuccessVerification.java
- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
> fix verify user by email

- src/main/java/com/softserve/teachua/dto/search/AdvancedSearchClubProfile.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
> changed advanced search by one age parametr

- src/main/resources/application.properties
> change application.properties

- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/ClubService.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
> Club service

- src/main/java/com/softserve/teachua/controller/StationController.java
- src/main/java/com/softserve/teachua/repository/StationRepository.java
- src/main/java/com/softserve/teachua/service/StationService.java
- src/main/java/com/softserve/teachua/service/impl/StationServiceImpl.java
> Advanced search add station 355

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/controller/CenterController.java
- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/converter/CenterToCenterResponseConverter.java
- src/main/java/com/softserve/teachua/converter/ClubToClubResponseConverter.java
- src/main/java/com/softserve/teachua/converter/ContactsStringConverter.java
- src/main/java/com/softserve/teachua/dto/center/CenterResponse.java
- src/main/java/com/softserve/teachua/dto/search/AdvancedSearchCenterProfile.java
- src/main/java/com/softserve/teachua/model/Center.java
- src/main/java/com/softserve/teachua/repository/CenterRepository.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/CenterService.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/resources/data.sql
> Center search

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/controller/CityController.java
> change security

- src/main/resources/application.yaml
> change application.yaml file

- src/main/java/com/softserve/teachua/dto/club/ClubProfile.java
> add field to dto class clubProfile

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
> fix security, add permitAll for /manifest.json and /favicon** and /logs

- src/main/java/com/softserve/teachua/dto/club/ClubProfile.java
- src/main/java/com/softserve/teachua/dto/location/LocationProfile.java
> Add validation for location name and age fields

- src/main/java/com/softserve/teachua/security/oauth2/CustomOAuth2UserService.java
- src/main/resources/application.properties
> change oauth2 application property

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
> add /verify url to security config

- src/main/java/com/softserve/teachua/service/impl/DataLoaderServiceImpl.java
> change replace

- src/main/java/com/softserve/teachua/service/impl/ExcelParserServiceImpl.java
> Fix empty category problem

- src/main/java/com/softserve/teachua/dto/location/LocationProfile.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
> fixed add club, added location strings

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
> fixed delete club for manager

- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
> fixed deleting club with locations

- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/DataLoaderServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ExcelParserServiceImpl.java
- src/main/resources/application-dev.properties
> implement searching by description field

- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/DistrictServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/StationServiceImpl.java
> fixed add club without location

- src/main/java/com/softserve/teachua/converter/CoordinatesConverter.java
- src/main/java/com/softserve/teachua/dto/location/LocationProfile.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
> add new class coordinates converter

- src/main/java/com/softserve/teachua/dto/club/ClubProfile.java
- src/main/java/com/softserve/teachua/model/Club.java
> validate Descript

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/dto/center/CenterProfile.java
- src/main/java/com/softserve/teachua/dto/center/SuccessCreatedCenter.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
> Add center

- src/main/java/com/softserve/teachua/controller/UploadController.java
- src/main/java/com/softserve/teachua/dto/club/ClubProfile.java
- src/main/java/com/softserve/teachua/dto/club/ClubResponse.java
- src/main/java/com/softserve/teachua/dto/club/SuccessCreatedClub.java
- src/main/java/com/softserve/teachua/dto/club/SuccessUpdatedClub.java
- src/main/java/com/softserve/teachua/dto/gallery/GalleryPhotoProfile.java
- src/main/java/com/softserve/teachua/model/Club.java
- src/main/java/com/softserve/teachua/model/GalleryPhoto.java
- src/main/java/com/softserve/teachua/repository/GalleryRepository.java
- src/main/java/com/softserve/teachua/service/FileUploadService.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/FileUploadServiceImpl.java
- src/main/resources/application-dev.properties
- src/main/resources/application-prod.properties
> Add gallery uploading

- src/main/java/com/softserve/teachua/model/Club.java
- src/main/java/com/softserve/teachua/service/impl/DataLoaderServiceImpl.java
> fix description

- src/main/java/com/softserve/teachua/model/Center.java
- src/main/java/com/softserve/teachua/service/impl/DataLoaderServiceImpl.java
> fix falidate by centers

- pom.xml
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/resources/application-dev.properties
> fix advance search with parameters and fix show clubs in the maps

- pom.xml
- src/main/java/com/softserve/teachua/controller/PasswordController.java
- src/main/java/com/softserve/teachua/controller/UserController.java
- src/main/java/com/softserve/teachua/dto/user/UserUpdateProfile.java
- src/main/java/com/softserve/teachua/dto/user/UserVerifyPassword.java
- src/main/java/com/softserve/teachua/service/UserService.java
- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
- src/test/java/com/softserve/teachua/service/UserServiceTest.java
> Fix user update profile

- pom.xml
> change version sprint parent

- src/main/java/com/softserve/teachua/dto/user/UserProfile.java
> add anotation to field password

- src/main/java/com/softserve/teachua/dto/user/UserProfile.java
> delete anotation to field password

- src/main/java/com/softserve/teachua/dto/user/UserPasswordReset.java
- src/main/java/com/softserve/teachua/dto/user/UserPasswordResetLogin.java
- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
> fix update user profile (new role name creation fix)

- src/main/java/com/softserve/teachua/model/User.java
> Fixed validation of firstName and lastName in User model

- src/main/java/com/softserve/teachua/repository/ClubRepository.java
> fix query advance search

- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
> fixed user logining via email

- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
> fixed password validation when register new user on back end

- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
> fixed security on backend for restoring password

- src/main/java/com/softserve/teachua/controller/SearchController.java
- src/main/java/com/softserve/teachua/exception/handler/CustomExceptionHandler.java
> Search 50 letters fixed

- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
> Email case sensetive bug fixed

- pom.xml
- src/main/java/com/softserve/teachua/exception/IncorrectInputException.java
- src/main/java/com/softserve/teachua/exception/handler/CustomExceptionHandler.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
> Added validation in addClub on empty mandatory field

- src/main/java/com/softserve/teachua/controller/UserController.java
- src/main/java/com/softserve/teachua/dto/user/UserPasswordUpdate.java
- src/main/java/com/softserve/teachua/dto/user/UserUpdateProfile.java
- src/main/java/com/softserve/teachua/exception/UpdatePasswordException.java
- src/main/java/com/softserve/teachua/exception/handler/CustomExceptionHandler.java
- src/main/java/com/softserve/teachua/service/UserService.java
- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
> Backend doesnt require existing password bug fixed

- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
> unlimited letters in age field fixed

- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
> null pointer exception fix

- src/main/java/com/softserve/teachua/exception/handler/CustomExceptionHandler.java
- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
> Create admin profile fixed

- src/main/java/com/softserve/teachua/controller/user/RegistrationController.java
> check pull

- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
> fixed add center bug #758

- src/main/java/com/softserve/teachua/controller/ClubController.java
> Update Delete Club check permissions

- src/main/java/com/softserve/teachua/dto/user/UserProfile.java
> add validation

- src/main/java/com/softserve/teachua/dto/club/ClubProfile.java
- src/main/java/com/softserve/teachua/dto/club/validation/ClubDescription.java
- src/main/java/com/softserve/teachua/dto/club/validation/DescriptionValidation.java
> Fix bug 857

- src/main/java/com/softserve/teachua/dto/center/CenterProfile.java
> added clubs validation

- pom.xml
- src/main/java/com/softserve/teachua/dto/challenge/CreateChallenge.java
- src/main/java/com/softserve/teachua/dto/challenge/UpdateChallenge.java
- src/main/java/com/softserve/teachua/dto/task/CreateTask.java
- src/main/java/com/softserve/teachua/dto/task/UpdateTask.java
- src/main/java/com/softserve/teachua/exception/handler/CustomExceptionHandler.java
- src/main/java/com/softserve/teachua/service/impl/FileUploadServiceImpl.java
> #907, #908, #910, #918 bugs fixed

- src/main/java/com/softserve/teachua/controller/ChallengeController.java
- src/main/java/com/softserve/teachua/controller/TaskController.java
- src/main/java/com/softserve/teachua/dto/challenge/ChallengeProfile.java
- src/main/java/com/softserve/teachua/repository/TaskRepository.java
- src/main/java/com/softserve/teachua/service/ChallengeService.java
- src/main/java/com/softserve/teachua/service/TaskService.java
- src/main/java/com/softserve/teachua/service/impl/ChallengeServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/TaskServiceImpl.java
Just remove task pagenation from DTO and some methods
> tasks pagenation removed

- src/main/java/com/softserve/teachua/Application.java
- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/controller/ChallengeController.java
- src/main/java/com/softserve/teachua/controller/TaskController.java
- src/main/java/com/softserve/teachua/controller/UploadController.java
- src/main/java/com/softserve/teachua/dto/challenge/ChallengePreview.java
- src/main/java/com/softserve/teachua/dto/challenge/CreateChallenge.java
- src/main/java/com/softserve/teachua/dto/challenge/SuccessUpdateChallengePreview.java
- src/main/java/com/softserve/teachua/service/ChallengeService.java
- src/main/java/com/softserve/teachua/service/TaskService.java
- src/main/java/com/softserve/teachua/service/impl/ChallengeServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/TaskServiceImpl.java
added updateTaskPreview
minor changes to dto to display tasks in challenge
> adding challenges & tasks

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
> secure /admin/** uri

- src/main/java/com/softserve/teachua/exception/NotVerifiedUserException.java
> Change "unconfirmed email exception" status from 500 to 403

- src/test/java/com/softserve/teachua/service/CityServiceTest.java
- src/test/java/com/softserve/teachua/service/ClubServiceTest.java
Updated test names for better understanding which results should be returned by methods.
> Tests updating

- src/main/java/com/softserve/teachua/service/impl/FileUploadServiceImpl.java
> const was comparing with const

- src/main/java/com/softserve/teachua/dto/club/validation/DescriptionValidation.java
Updated club description validation for typing russian letters.
> club description validation is updated

- src/main/java/com/softserve/teachua/exception/MatchingPasswordException.java
- src/main/java/com/softserve/teachua/exception/handler/CustomExceptionHandler.java
- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
> Removed comparing old password with new in ResetPassword

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
just add /challenge/task/id to secure config
> Challenge secur fix

- src/main/java/com/softserve/teachua/dto/club/validation/DescriptionValidation.java
> fixed bad regular expression

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/dto/challenge/SuccessUpdatedChallenge.java
- src/main/java/com/softserve/teachua/dto/challenge/UpdateChallenge.java
> adding task security permissions

- src/main/java/com/softserve/teachua/dto/complaint/ComplaintProfile.java
- src/main/java/com/softserve/teachua/dto/feedback/FeedbackProfile.java
- src/main/java/com/softserve/teachua/service/impl/ComplaintServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/FeedbackServiceImpl.java
Fixed situation when the user can add complaint or feedback to non-exist userId or clubId
> Fixed #1044

- src/main/java/com/softserve/teachua/controller/CenterController.java
- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/dto/center/SuccessCreatedCenter.java
- src/main/java/com/softserve/teachua/exception/NotVerifiedUserException.java
- src/main/java/com/softserve/teachua/exception/handler/CustomExceptionHandler.java
- src/main/java/com/softserve/teachua/service/CenterService.java
- src/main/java/com/softserve/teachua/service/ClubService.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/test/java/com/softserve/teachua/service/CenterServiceTest.java
- src/test/java/com/softserve/teachua/service/ClubServiceTest.java
> During creation center and club userId = current userId

- src/main/java/com/softserve/teachua/controller/ChallengeController.java
- src/main/java/com/softserve/teachua/dto/challenge/CreateChallenge.java
- src/main/java/com/softserve/teachua/dto/challenge/UpdateChallenge.java
- src/main/java/com/softserve/teachua/dto/task/CreateTask.java
- src/main/java/com/softserve/teachua/dto/task/UpdateTask.java
- src/main/java/com/softserve/teachua/service/UserService.java
- src/main/java/com/softserve/teachua/service/impl/ChallengeServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/TaskServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
- src/main/java/com/softserve/teachua/utils/HtmlUtils.java
- src/main/java/com/softserve/teachua/utils/deserializers/HtmlModifyDeserialize.java
- src/main/java/com/softserve/teachua/utils/deserializers/TrimDeserialize.java
Some changes in HTML validator. Class HtmlValidator changed into HtmlUtils.
Created package deserializes and TrimHtmlModifyDeserializer moved into it. 
Added new deserializer to change some tags in HTML (HtmlModifyDeserialize.class).
An added feature to deny access to challenge if it is inactive and to task, if it does not start and the user is not admin.
> major changes in htmlutils

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/controller/BannerItemController.java
- src/main/java/com/softserve/teachua/dto/banner_item/BannerItemProfile.java
- src/main/java/com/softserve/teachua/dto/banner_item/BannerItemResponse.java
- src/main/java/com/softserve/teachua/dto/banner_item/SuccessCreatedBannerItem.java
- src/main/java/com/softserve/teachua/model/BannerItem.java
- src/main/java/com/softserve/teachua/repository/BannerItemRepository.java
- src/main/java/com/softserve/teachua/service/BannerItemService.java
- src/main/java/com/softserve/teachua/service/impl/BannerItemServiceImpl.java
- src/test/java/com/softserve/teachua/service/BannerItemServiceTest.java
> developed functionality for banner

- src/main/java/com/softserve/teachua/dto/challenge/UpdateChallenge.java
> just removed useless field

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/controller/CenterController.java
- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/controller/FeedbackController.java
- src/main/java/com/softserve/teachua/dto/club/ClubResponse.java
- src/main/java/com/softserve/teachua/model/Center.java
- src/main/java/com/softserve/teachua/model/Club.java
- src/main/java/com/softserve/teachua/repository/CenterRepository.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/repository/FeedbackRepository.java
- src/main/java/com/softserve/teachua/service/CenterService.java
- src/main/java/com/softserve/teachua/service/ClubService.java
- src/main/java/com/softserve/teachua/service/FeedbackService.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/FeedbackServiceImpl.java
- src/test/java/com/softserve/teachua/service/FeedbackServiceTest.java
> Club center rating

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
Just added url /challenge/** and /challenge/task/**(yes, i know that it is a overkill) to SecurityConfig
> Front task sec

- src/main/java/com/softserve/teachua/service/impl/ComplaintServiceImpl.java
> force initialization date for complaint

- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/FeedbackServiceImpl.java
> Fixed adding feedbacks to club that not belong to center

- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/impl/FeedbackServiceImpl.java
- src/test/java/com/softserve/teachua/service/FeedbackServiceTest.java
> fixed bugs

- src/main/java/com/softserve/teachua/dto/club/validation/CheckRussianValidator.java
An error that prevents the creation of a club
> Fix Validator

- src/test/java/com/softserve/teachua/service/DistrictServiceTest.java
> tests for DistrictServiceImpl

- src/test/java/com/softserve/teachua/service/StationServiceImplTest.java
> tests for StationServiceImpl

- src/main/java/com/softserve/teachua/dto/user/UserProfile.java
- src/main/java/com/softserve/teachua/dto/user/UserUpdateProfile.java
- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
- src/main/java/com/softserve/teachua/utils/validations/Name.java
- src/main/java/com/softserve/teachua/utils/validations/NameValidator.java
Updated register user profile validation including password validation on backend and frontend
> updated register user profile validation

- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
the method is not used for a long time
> the method is not used

- src/main/java/com/softserve/teachua/dto/task/TaskProfile.java
- src/main/java/com/softserve/teachua/model/Challenge.java
- src/main/java/com/softserve/teachua/model/Task.java
- src/main/java/com/softserve/teachua/service/impl/TaskServiceImpl.java
- src/test/java/com/softserve/teachua/service/TaskServiceTest.java
> tests for TaskServiceImpl

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
> Stations are not displayed for unauthorized user

- src/main/java/com/softserve/teachua/dto/location/LocationResponse.java
> Add cityResponse to LocationResponse

- src/main/java/com/softserve/teachua/service/AboutUsItemService.java
- src/main/java/com/softserve/teachua/service/impl/AboutUsItemServiceImpl.java
- src/test/java/com/softserve/teachua/service/impl/AboutUsItemServiceImplTest.java
> Tests for AboutUsItemServiceImpl

- checkstyle.xml
- pom.xml
> created checkstyle configurations

- src/main/java/com/softserve/teachua/dto/complaint/ComplaintProfile.java
- src/main/java/com/softserve/teachua/service/impl/ComplaintServiceImpl.java
Deleted  time field from DTO and initialize it automatically
> Deleted Time From DTO

- .github/workflows/tests.yml
- README.md
I was added .yaml file to configure github actions to run tests using maven
> yaml file to run tests added

- .github/workflows/style.yml
Check style action added
And test action fixed
> tests action fixed and style action added

- .gitignore
- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/controller/NewsController.java
- src/main/java/com/softserve/teachua/dto/news/NewsProfile.java
- src/main/java/com/softserve/teachua/dto/news/NewsResponse.java
- src/main/java/com/softserve/teachua/dto/news/SuccessCreatedNews.java
- src/main/java/com/softserve/teachua/model/News.java
- src/main/java/com/softserve/teachua/service/NewsService.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/NewsServiceImpl.java
> News update

- src/main/java/com/softserve/teachua/controller/ClubController.java
Need to use custom annotation for secure method
> Fix annotation

- src/test/java/com/softserve/teachua/service/FeedbackServiceTest.java
One test method had been throwing exception, now it is fine
> Fix tests feedback service

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/resources/application-prod.properties
> added swagger config to prod

- src/main/java/com/softserve/teachua/controller/marker/Api.java
- src/main/resources/application-dev.properties
- src/main/resources/application-prod.properties
added http + https support by adding servers
> Add swagger servers

- src/test/java/com/softserve/teachua/repository/BannerItemRepositoryIT.java
- src/test/java/com/softserve/teachua/repository/CityRepositoryIT.java
> created integration tests

- src/main/java/com/softserve/teachua/dto/club/ClubProfile.java
- src/main/java/com/softserve/teachua/dto/club/validation/DescriptionValidation.java
- src/test/java/com/softserve/teachua/service/FeedbackServiceTest.java
corrected @ClubDescription annotation
removed @Mock annotation from variable
> Minor bugs fix

- src/test/java/com/softserve/teachua/repository/CityRepositoryIT.java
> updated test

- src/main/java/com/softserve/teachua/controller/ClubController.java
- src/main/java/com/softserve/teachua/utils/annotation/AllowedRolesAspect.java
Extra: I corrected javaDocs which I had spoiled
> Allowed roles throwed 500 status

- src/main/java/com/softserve/teachua/controller/AddressController.java
- src/main/java/com/softserve/teachua/dto/location/AddressProfile.java
- src/main/java/com/softserve/teachua/repository/CityRepository.java
- src/main/java/com/softserve/teachua/service/AddressService.java
- src/main/java/com/softserve/teachua/service/impl/AddressServiceImpl.java
Controller for fixing incorrect address in DB
> Comparing incorrect address

- src/main/java/com/softserve/teachua/dto/location/LocationProfile.java
> remove @NotBlank annotation

- src/main/java/com/softserve/teachua/controller/AddressController.java
Added import to address controller
> Add imports for annotations

- src/main/java/com/softserve/teachua/controller/StationController.java
- src/main/java/com/softserve/teachua/dto/station/StationProfile.java
- src/main/java/com/softserve/teachua/dto/station/StationResponse.java
- src/main/java/com/softserve/teachua/dto/station/SuccessCreatedStation.java
- src/main/java/com/softserve/teachua/model/Station.java
- src/main/java/com/softserve/teachua/repository/StationRepository.java
- src/main/java/com/softserve/teachua/service/StationService.java
- src/main/java/com/softserve/teachua/service/impl/StationServiceImpl.java
Added controller for link between district and station
> Created link for station

- src/main/java/com/softserve/teachua/controller/LogController.java
- src/main/java/com/softserve/teachua/dto/log/LogResponse.java
- src/main/java/com/softserve/teachua/service/LogService.java
- src/main/java/com/softserve/teachua/service/impl/LogServiceImpl.java
Created  endpoint for log deliting
Created endpoint for checking path to logs  in dev&prod version
> Update deleting logs

- src/main/java/com/softserve/teachua/controller/LogController.java
- src/main/java/com/softserve/teachua/service/LogService.java
- src/main/java/com/softserve/teachua/service/impl/LogServiceImpl.java
Updated delete all in service layer
Added creating directory by parameter
> Added creating sub directory by Parameter directoryName

- src/main/java/com/softserve/teachua/controller/LogController.java
- src/main/java/com/softserve/teachua/service/LogService.java
- src/main/java/com/softserve/teachua/service/impl/LogServiceImpl.java
Created Put controller for moving logs to existing sub directory
> Create moving logs to sub directory

- src/main/java/com/softserve/teachua/controller/LogController.java
- src/main/java/com/softserve/teachua/service/AddressService.java
- src/main/java/com/softserve/teachua/service/LogService.java
- src/main/java/com/softserve/teachua/service/impl/LogServiceImpl.java
Added Deliting empty log for custom use.
> Deleting empty logs

- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
- src/test/java/com/softserve/teachua/service/AboutUsItemServiceImplTest.java
- src/test/java/com/softserve/teachua/service/BannerItemServiceTest.java
- src/test/java/com/softserve/teachua/service/CategoryServiceTest.java
- src/test/java/com/softserve/teachua/service/CenterServiceTest.java
- src/test/java/com/softserve/teachua/service/CityServiceTest.java
- src/test/java/com/softserve/teachua/service/ClubServiceTest.java
- src/test/java/com/softserve/teachua/service/ComplaintServiceTest.java
- src/test/java/com/softserve/teachua/service/RoleServiceTest.java
- src/test/java/com/softserve/teachua/service/UserServiceTest.java
I changed the implementation of archiving, but I forgot to change the tests. Now I've fixed it.
> Fix service tests

- src/main/java/com/softserve/teachua/tools/transfer_controller/BannerTransferController.java
- src/main/java/com/softserve/teachua/tools/transfer_model/BannerItemTransfer.java
> Added package for Transfer Models

- src/main/java/com/softserve/teachua/tools/FileReader.java
- src/main/java/com/softserve/teachua/tools/transfer_service/transfer_impl/TaskTransferServiceImpl.java
- src/main/resources/task_res.txt
1) create file in resources
2) one object - one line
3) give only name of file
4) example in file TaskTransferServiceImpl
5) later I wil refactor FileReader
> File reader

- src/main/java/com/softserve/teachua/tools/FileUtils.java
- src/main/java/com/softserve/teachua/tools/transfer_service/transfer_impl/TaskTransferServiceImpl.java
- src/main/resources/task_res.txt
1) In dtos (hardcode) input path to images in resources (images_to_db/image.jpg)
2) Use function moveImage "folder" - where image will moved "target/upload/"folder"/image.jpg"
> Imge transferring

- src/main/java/com/softserve/teachua/tools/FileUtils.java
- src/main/resources/task_res.txt
now it save path like: /upload/....
> Fix move image

- src/main/java/com/softserve/teachua/tools/transfer_controller/BannerTransferController.java
- src/main/java/com/softserve/teachua/tools/transfer_model/BannerItemTransfer.java
- src/main/java/com/softserve/teachua/tools/transfer_service/BannerItemTransferService.java
- src/main/java/com/softserve/teachua/tools/transfer_service/transfer_impl/BannerItemTransferServiceImpl.java
Added functional for move banner to DB
> Added hardCODE for banners

- src/main/java/com/softserve/teachua/tools/transfer_repository/MoveBannerRepository.java
- src/main/java/com/softserve/teachua/tools/transfer_service/transfer_impl/BannerItemTransferServiceImpl.java
> Split Resource & Implementation

- src/main/java/com/softserve/teachua/tools/info_repository/BannerInfoRepository.java
- src/main/java/com/softserve/teachua/tools/transfer_controller/BannerTransferController.java
- src/main/java/com/softserve/teachua/tools/transfer_service/BannerItemTransferService.java
- src/main/java/com/softserve/teachua/tools/transfer_service/transfer_impl/BannerItemTransferServiceImpl.java
> Updated Banner Repository

- src/main/java/com/softserve/teachua/controller/LogController.java
- src/main/java/com/softserve/teachua/service/impl/LogServiceImpl.java
Added JavaDoc to log controller
Refactored log services
> Upgraded log functional

- src/main/java/com/softserve/teachua/dto/center/CenterProfile.java
- src/main/java/com/softserve/teachua/dto/location/LocationProfile.java
- src/main/java/com/softserve/teachua/service/impl/CenterServiceImpl.java
moved location method  to external place
> Refactored center update

- src/main/java/com/softserve/teachua/controller/UserController.java
It is bad practic to send model on front-end so I wanted change it to dto. Hovewer this method isnt used on front-end and is used on back-end, where needed whole model. So I decieded to delete this controller method.
> This method isn't used on front

- src/main/java/com/softserve/teachua/controller/UserController.java
- src/main/java/com/softserve/teachua/dto/user/UserUpdateProfile.java
- src/main/java/com/softserve/teachua/service/impl/RoleServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
- src/test/java/com/softserve/teachua/service/UserServiceTest.java
Fixed phone validation for User
Deleted adding string with "38" to user phone number
Added Prefix for user role for finding roles
> Fixed User phone & role

- src/main/java/com/softserve/teachua/dto/user/UserProfile.java
Fixed number of digit according to frontend
> Fix phone for registration

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
Problem - authentication via socials wasnt working
> Fix oAuth2

- .github/workflows/sonar-cloud.yml
I mistakenly merged in branch that I didn't want to merge
> Revert "Update sonar-cloud.yml"

- src/main/java/com/softserve/teachua/service/impl/AddressServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/BackupServiceImpl.java
Update address service
Update backup service
> Fix NPE AddressCotroller

- src/main/java/com/softserve/teachua/service/impl/BackupServiceImpl.java
Fixed wrong path to image directory
> Fix wrog path for backup

- src/main/java/com/softserve/teachua/dto/search/AdvancedSearchClubProfile.java
- src/main/java/com/softserve/teachua/repository/ClubRepository.java
- src/main/java/com/softserve/teachua/service/impl/ClubServiceImpl.java
- src/test/java/com/softserve/teachua/repository/ClubRepositoryIT.java
- src/test/java/com/softserve/teachua/repository/utils/club_test_data/ClubSearchTestEntity.java
dev
Update advanced search
ToDo
Add name to advanced serach
ToDo
> Ubdate advanced search

- src/main/java/com/softserve/teachua/service/impl/ChallengeServiceImpl.java
- src/main/java/com/softserve/teachua/utils/ChallengeUtil.java
dev
Sort numbers must be >0 and be unique
Add validation for sortNumbers in Challenges
> Add validation for sortnumbers in challenges

- src/main/java/com/softserve/teachua/repository/TaskRepository.java
- src/main/java/com/softserve/teachua/service/impl/ChallengeServiceImpl.java
> Change order by date task in challenge page

- src/main/java/com/softserve/teachua/Application.java
- src/main/java/com/softserve/teachua/config/ApplicationConfig.java
- src/main/java/com/softserve/teachua/dto/task/CreateTask.java
- src/main/java/com/softserve/teachua/utils/validations/CheckForeignLanguageValidator.java
> fixed regexp in lang validator

- src/main/java/com/softserve/teachua/controller/ChallengeController.java
- src/main/java/com/softserve/teachua/dto/challenge/UpdateChallengeDate.java
- src/main/java/com/softserve/teachua/service/ChallengeService.java
- src/main/java/com/softserve/teachua/service/impl/ChallengeServiceImpl.java
- src/test/java/com/softserve/teachua/service/TaskServiceTest.java
> Clone challenge

- src/main/java/com/softserve/teachua/controller/ScheduleSendEmailController.java
- src/main/java/com/softserve/teachua/service/impl/ScheduleSendServiceImpl.java
> ScheduleSendServiceImpl update methods

- src/main/java/com/softserve/teachua/controller/ScheduleSendEmailController.java
- src/main/java/com/softserve/teachua/repository/CertificateRepository.java
- src/main/java/com/softserve/teachua/service/CertificateService.java
- src/main/java/com/softserve/teachua/service/EmailService.java
- src/main/java/com/softserve/teachua/service/ScheduleSendService.java
- src/main/java/com/softserve/teachua/service/impl/CertificateServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/EmailServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/ScheduleSendServiceImpl.java
- src/main/resources/certificates/templates/jedyni_participant_template.jrxml
> Certificates generation

- src/main/java/com/softserve/teachua/controller/CertificateController.java
- src/main/java/com/softserve/teachua/repository/CertificateRepository.java
- src/main/java/com/softserve/teachua/service/CertificateService.java
- src/main/java/com/softserve/teachua/service/impl/CertificateServiceImpl.java
> Added certificate search for users functionality

- src/main/java/com/softserve/teachua/service/impl/CertificateExcelServiceImpl.java
- src/main/java/com/softserve/teachua/utils/validations/CertificateUserNameValidator.java
> Fixed certificate generation for double first/last names

- src/main/resources/certificates/templates/jedyni_participant_template.jrxml
- src/main/resources/certificates/templates/moderator_certificate.jrxml
- src/main/resources/certificates/templates/trainer_certificate.jrxml
dev
Had to change position of few text elemets in xml templates
Changed three template files, moved text
ToDo
> Changed templates, moved text elements

- src/main/java/com/softserve/teachua/service/impl/UserServiceImpl.java
> Fixed email html encoding

- src/main/java/com/softserve/teachua/controller/CertificateController.java
- src/main/java/com/softserve/teachua/dto/certificate/CertificateUserResponse.java
- src/main/java/com/softserve/teachua/service/CertificateService.java
- src/main/java/com/softserve/teachua/service/impl/CertificateServiceImpl.java
> Download certificate by id instead of serialNumber

- src/main/java/com/softserve/teachua/repository/CertificateRepository.java
- src/main/java/com/softserve/teachua/service/CertificateService.java
- src/main/java/com/softserve/teachua/service/LogService.java
- src/main/java/com/softserve/teachua/service/impl/CertificateServiceImpl.java
> Return only certificates with serial number

- src/main/java/com/softserve/teachua/repository/CertificateRepository.java
- src/main/java/com/softserve/teachua/service/impl/CertificateServiceImpl.java
> Updated certificate send status after download

- src/main/java/com/softserve/teachua/controller/test/QuestionsController.java
- src/main/java/com/softserve/teachua/dto/test/question/ImportProfile.java
- src/main/java/com/softserve/teachua/dto/test/question/QuestionPreview.java
- src/main/java/com/softserve/teachua/service/test/QuestionService.java
- src/main/java/com/softserve/teachua/service/test/impl/QuestionServiceImpl.java
> Updated tool for import questions from google form

- src/main/java/com/softserve/teachua/config/SecurityConfig.java
- src/main/java/com/softserve/teachua/dto/user/SuccessLogin.java
- src/main/java/com/softserve/teachua/security/JwtProvider.java
- src/main/java/com/softserve/teachua/security/oauth2/OAuth2AuthenticationSuccessHandler.java
> Admin security fix and return role on login 

- src/main/java/com/softserve/teachua/config/ConfigureIMAPProperties.java
- src/main/java/com/softserve/teachua/exception/handler/CustomExceptionHandler.java
- src/main/java/com/softserve/teachua/repository/CertificateRepository.java
- src/main/java/com/softserve/teachua/repository/MessageRepository.java
- src/main/java/com/softserve/teachua/security/oauth2/CustomOAuth2UserService.java
- src/main/java/com/softserve/teachua/service/impl/GmailServiceImpl.java
- src/main/java/com/softserve/teachua/service/impl/MessageServiceImpl.java
> Return sorted messages and fixed http status code on exceptions
